### PR TITLE
Public and Private Routing

### PR DESCRIPTION
**Pull request by sndadda**
So far:
- If user is not logged in, they can only access / and /Signup.
- If they are logged in and have completed the profile creation flow, redirected to create-profile (or /matching ig)
- If logged in but is missing any one of the profile-creation pages, they're redirected to that page and in order of the flow as well.
- Added extra field in database for uploading pictures page for routing logic. So spotifyLinked, foodChosen, and picturesUploaded all have to be true for user to go forward to /matching, user can still go to /create-profile for user to logout which can be changed if needed, i didn't know what /create-profile exactly was for.

- Fixed loading bug in Routes.js 
- Fixed /food bugs I saw

### CODE REVIEW

**Comment by armandoparra13** [comment]
image

on `http://localhost:3000/`, I am stuck seeing this

**Comment by armandoparra13** [comment]
I also noticed Auth.js was moved out of `./front/contexts` into `./front`

**Comment by sndadda** [comment]
Fixed loading issue and also deleted contexts/auth

**Review by armandoparra13 — APPROVED** [review]
I havent found a way to break it

**Comment by sndadda** [comment]
SCOREEEEE

**Pull request merged**
